"""initial migration

Revision ID: 3dc5c070dd11
Revises: 
Create Date: 2025-10-10 10:07:42.808191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3dc5c070dd11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pension_payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('age_bracket', sa.String(length=20), nullable=False),
    sa.Column('pension_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pension_payouts_id'), 'pension_payouts', ['id'], unique=False)
    op.drop_table('pension_premium_plans')
    op.add_column('pension_entry_ages', sa.Column('monthly_premium', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('pension_entry_ages', sa.Column('num_of_monthly_installments', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('pension_entry_ages', sa.Column('semi_annual_premium', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('pension_entry_ages', sa.Column('num_of_semi_annual_installments', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('pension_entry_ages', sa.Column('lump_sum_payment', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('pension_entry_ages', 'years_to_60')
    op.drop_column('pension_entry_ages', 'premium_for_5000')
    op.drop_column('pension_entry_ages', 'premium_for_1000')
    op.drop_column('pension_entry_ages', 'premium_for_2500')
    op.drop_column('pension_entry_ages', 'premium_for_10000')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_entry_ages', sa.Column('premium_for_10000', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('pension_entry_ages', sa.Column('premium_for_2500', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('pension_entry_ages', sa.Column('premium_for_1000', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('pension_entry_ages', sa.Column('premium_for_5000', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('pension_entry_ages', sa.Column('years_to_60', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pension_entry_ages', 'lump_sum_payment')
    op.drop_column('pension_entry_ages', 'num_of_semi_annual_installments')
    op.drop_column('pension_entry_ages', 'semi_annual_premium')
    op.drop_column('pension_entry_ages', 'num_of_monthly_installments')
    op.drop_column('pension_entry_ages', 'monthly_premium')
    op.create_table('pension_premium_plans',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('monthly_premium', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_pension_payouts_id'), table_name='pension_payouts')
    op.drop_table('pension_payouts')
    # ### end Alembic commands ###
