"""create new pensiopremiumen scheme tables

Revision ID: e4a54d696fb9
Revises: 3dc5c070dd11
Create Date: 2025-10-10 10:08:16.145211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a54d696fb9'
down_revision: Union[str, None] = '3dc5c070dd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
